// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkLgzYVSmvCmkqlrkc0aIfNTgBhq7UPKw',
    appId: '1:865188548362:web:ed08135be5cdead374f4f3',
    messagingSenderId: '865188548362',
    projectId: 'fir-b9203',
    authDomain: 'fir-b9203.firebaseapp.com',
    storageBucket: 'fir-b9203.appspot.com',
    measurementId: 'G-0H1W73J6V6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqqxcP3GCNT73RsU1ZLty3iLAmithUclg',
    appId: '1:865188548362:android:81b426e974c497eb74f4f3',
    messagingSenderId: '865188548362',
    projectId: 'fir-b9203',
    storageBucket: 'fir-b9203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB61QDjKnY8Qh1FCmFUSHsbd13bMbugDlQ',
    appId: '1:865188548362:ios:448a69fa9aa3a21774f4f3',
    messagingSenderId: '865188548362',
    projectId: 'fir-b9203',
    storageBucket: 'fir-b9203.appspot.com',
    iosBundleId: 'com.example.profileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB61QDjKnY8Qh1FCmFUSHsbd13bMbugDlQ',
    appId: '1:865188548362:ios:0ccb0fc9f1058e6674f4f3',
    messagingSenderId: '865188548362',
    projectId: 'fir-b9203',
    storageBucket: 'fir-b9203.appspot.com',
    iosBundleId: 'com.example.profileApp.RunnerTests',
  );
}
